export function displayLog(elemento: string){
    let div = document.querySelector('#log-container');
    let content = document.createElement('div');
    content.innerHTML = `<div>${elemento}</div>`;
    // console.log(elemento);
    div?.appendChild(content);
}

export const lorem = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit eligendi quas nesciunt aut earum quos numquam aspernatur veniam accusantium ratione, quidem error reprehenderit possimus reiciendis vero esse cum laboriosam ipsum. Corrupti voluptate
id quaerat vero quibusdam recusandae incidunt ut, necessitatibus eos quam minima libero? Vero, dignissimos repellendus ipsa iste ad recusandae, earum architecto iusto impedit blanditiis, quos ipsam temporibus? Alias. Maiores cumque eos odio
nostrum magni temporibus repellat eius inventore eligendi nesciunt fugiat eveniet explicabo, vel deserunt molestias consectetur quis debitis excepturi assumenda officiis corrupti pariatur ducimus amet! Neque, repudiandae! Cum, quia, nam iusto
voluptatem quis quae ab perferendis aperiam consequatur officiis fugit ipsam unde molestiae nisi. Necessitatibus illum, culpa maiores sit soluta sequi molestiae quo, nihil commodi expedita perspiciatis. Sapiente molestiae aspernatur quia excepturi,
incidunt quos, illum vitae praesentium perspiciatis, aperiam odit distinctio minima architecto libero! Officiis, vero, architecto incidunt beatae consequatur expedita voluptates omnis ullam maiores, dolore doloremque. Delectus libero impedit,
omnis cum illo iusto aliquam hic atque id quidem natus quisquam, error dolorem voluptatum optio voluptas quae itaque sit voluptatem inventore ea quis excepturi nihil eaque. Ipsa? Explicabo laborum neque voluptatum tempora minima unde veniam.
Veritatis qui impedit nulla hic odit odio quas! Minus, sapiente, commodi laborum aliquid facilis esse eos error voluptatum eum praesentium doloribus asperiores? Hic non animi cumque veritatis quibusdam! Natus at consectetur quibusdam accusantium
iusto architecto cum reiciendis dolorum modi! Explicabo vel cumque aliquid culpa. Corrupti fuga sit optio assumenda pariatur. Non, expedita? Reiciendis vitae nemo enim ipsam autem facere officia amet alias ab in aut incidunt iure praesentium
ea ex quam at, fugit illum tempora, minima, consequatur expedita sunt cum delectus! Perspiciatis? Pariatur omnis quis natus culpa at totam vitae nesciunt aliquam tenetur vero! Voluptas sunt beatae quidem placeat architecto cumque, nemo temporibus
quas eos incidunt, vel animi enim odit explicabo. Temporibus. Quis ex aut architecto repellendus cupiditate. Officiis nam repellendus facilis voluptate reiciendis? Aperiam modi, facere minima, dicta dignissimos rem accusantium a numquam assumenda
similique corporis deleniti fugiat suscipit maxime consequatur! Labore, tempora nam modi natus possimus enim explicabo similique, temporibus iure quidem ratione commodi odio corporis neque esse asperiores est ad iste saepe incidunt aut quisquam
consequuntur ab? Consectetur, molestiae! Harum praesentium maiores dolor consequuntur nihil vero ea, cum adipisci quod quos, repellat obcaecati incidunt fuga! Hic culpa, quo at mollitia a iste nihil necessitatibus veritatis explicabo. Iure,
necessitatibus dolore. Architecto minus aliquam quae quo aut animi at minima distinctio delectus saepe non inventore unde nulla iure, ratione asperiores provident eius ullam voluptates amet iusto ex? Libero nisi quaerat deleniti! Nulla, libero?
Excepturi placeat, similique aliquam tempore porro at officiis facere voluptatibus sint impedit! Quos laboriosam cumque quis eveniet? Corrupti, sint numquam illum vitae iusto aliquam assumenda itaque quod doloremque! Obcaecati eveniet deleniti
dolorum provident asperiores reiciendis dolore, placeat cupiditate eaque iusto nulla totam fuga, dicta quos sint at accusantium, aliquam quasi modi molestiae iure omnis alias laborum neque? Nostrum. Porro, eos possimus. Quod id reprehenderit
quos fuga quas incidunt cum reiciendis, iste iure perferendis cupiditate in animi. Accusamus vel nostrum officiis voluptate debitis praesentium et non eum! Temporibus, obcaecati. Doloribus, voluptates. Repellat debitis asperiores, atque voluptatem
reprehenderit aspernatur voluptate, veniam vel voluptatum enim, sed error odit quod similique id. Voluptatem magnam explicabo culpa eius recusandae impedit aperiam iste non? Sed vero porro nulla voluptate numquam! Ipsam quod dicta tempore
quae ut aliquam sapiente in nostrum sequi, itaque ipsum saepe cupiditate minima odio cumque beatae aperiam! Maiores quasi nam architecto. Quasi, sunt delectus repudiandae amet similique voluptatibus omnis ad consectetur ab! Doloribus, velit.
Ea quia commodi dolorem beatae odio vel dicta harum consequuntur, sunt deserunt, aliquid quaerat architecto accusantium ab! Reprehenderit quas eius repellat deserunt quo autem, placeat alias temporibus quos. Expedita praesentium nesciunt quam
cumque iste facere rem asperiores odit recusandae, incidunt velit, earum dolorum suscipit nulla cupiditate voluptates? Sed quo saepe fugiat cum ipsa quisquam debitis. Suscipit laudantium ipsa tempore quas consequatur quis quasi quidem, voluptatem
culpa, excepturi, corrupti quaerat officiis molestiae repellendus pariatur ab. Ea, optio excepturi! Nulla, dignissimos soluta. Alias blanditiis ab sunt quod vero saepe accusantium quos dolorem molestiae deleniti ipsam nostrum at cupiditate
tenetur molestias delectus debitis, atque omnis! Quia ratione cum doloribus maiores. Cum iste, odit ex quibusdam, commodi quaerat eum placeat laborum, asperiores perspiciatis possimus voluptates tenetur explicabo. Non sapiente labore aperiam
dolores rem soluta. Molestiae expedita similique ad eum. Mollitia, vero? Expedita totam deserunt dolor qui quibusdam id repellat adipisci exercitationem ab facilis corrupti ratione aliquid, nemo culpa accusamus ad fugiat asperiores architecto
quaerat consequuntur! Modi est ipsum eaque nihil libero! Esse dolore dolorum perferendis commodi quae laudantium corrupti necessitatibus nostrum. Facere ab aut, aperiam ea consequatur deleniti ullam officia non sit quod minima cum perferendis,
mollitia sed. Tempora, nam cum. Eum fugit adipisci doloremque perferendis suscipit delectus, velit deleniti quod quis quae nihil! Suscipit alias commodi molestiae et, aspernatur vitae cumque, temporibus deserunt vero eaque dolorum maxime porro
ab impedit! Accusantium earum, ratione architecto natus aperiam quod, aliquam similique possimus nihil maiores mollitia odit laudantium sed officiis fuga eaque. Pariatur fugiat enim esse optio cum, nam inventore corrupti deleniti facilis!
Incidunt vero ipsam odit in, quidem molestiae ipsum? Sunt dicta est nesciunt laboriosam! Perspiciatis excepturi, id doloribus voluptatibus tempora debitis magni earum reprehenderit veritatis eos magnam, porro veniam velit minima. Consequuntur
repellat velit nulla quis, voluptas ea, harum placeat tempora aliquid sunt eveniet deserunt inventore rem natus quisquam magni voluptates officia sequi possimus eum. Reiciendis aut corporis earum qui aspernatur. Amet ea eius velit! Eius in
mollitia voluptate, aliquid accusamus autem natus minus deserunt expedita nesciunt id cum magnam, rem, aspernatur doloribus repellendus? Ut a quisquam impedit maiores qui facilis? Quaerat, eius mollitia voluptatibus commodi voluptatem sequi
blanditiis praesentium neque et similique doloremque animi sit tenetur eum minus enim laborum in ullam voluptas architecto consequuntur deserunt aut. Laborum, nostrum commodi. Porro aut optio quo veritatis nesciunt commodi, cupiditate aliquid
voluptatem laudantium eius, cumque vel qui ex alias non odit rerum beatae inventore? Quos tempore dolorem, possimus similique incidunt mollitia reiciendis? Itaque alias quam facilis iste repudiandae magnam quibusdam voluptas tempora voluptate,
aspernatur, enim facere officia exercitationem neque eligendi non, quae esse excepturi necessitatibus ad est libero velit totam sit. Necessitatibus. Eveniet voluptate quis, ullam culpa recusandae odit perferendis nulla alias asperiores ipsa,
dignissimos ab. Libero, cupiditate voluptatem minima obcaecati, eligendi odit vitae tenetur porro quod fuga numquam quaerat vel at? Officiis aliquid unde ab quo molestias maiores quam temporibus soluta enim doloribus laudantium, vitae optio
laborum! Deserunt quasi voluptates facere, quas tempora voluptatum alias aut in. Quisquam doloribus excepturi vel? Optio natus, repellat dolor asperiores, similique nostrum in voluptate at quisquam necessitatibus porro mollitia voluptatem
voluptas pariatur consequatur, magni voluptates earum itaque labore quis aliquam quibusdam quas! Voluptatibus, quam ipsum! Ex delectus natus, et iure reprehenderit neque eveniet consequatur voluptate omnis iusto magni odit modi enim saepe.
Animi dolores ad odit corrupti, id quas vero repudiandae nemo labore cupiditate numquam! Dolorum dolor commodi minima sapiente error aperiam ad molestiae repellendus velit consequatur nisi earum voluptas, similique, libero tempora deserunt
neque accusantium optio necessitatibus enim maxime cupiditate. Mollitia pariatur consectetur minima. Neque explicabo necessitatibus dolore, itaque molestias recusandae ea quos iure. Repudiandae, beatae neque consectetur obcaecati, illo architecto
nisi nam eaque doloremque distinctio magni rerum excepturi reiciendis dicta odio quod unde. Labore, voluptate iure ducimus maxime similique facere est hic exercitationem accusamus earum reprehenderit atque velit eum, minima repellat, nihil
a? Explicabo illo corporis repudiandae nisi praesentium? Inventore sapiente dolor itaque! Culpa quibusdam illum autem tempore voluptatem corporis nam excepturi doloribus est consequuntur vero, hic dicta voluptatibus, accusamus quisquam dignissimos
voluptatum reprehenderit. Pariatur, accusantium aspernatur dignissimos sint quisquam qui eum error! Mollitia, illum! Nulla placeat asperiores at repellendus facilis cum ipsum quod obcaecati repellat ad quia hic commodi eius voluptate nam perspiciatis
in, possimus eum quidem atque labore ratione consectetur minima. Eos ipsa ducimus voluptatibus, odit impedit quo fugiat iure, ipsum dolore velit a accusamus odio deleniti nemo, fugit quae qui ea provident beatae eius necessitatibus. Amet eos
voluptas beatae quaerat. Accusamus dolorum quidem veritatis animi dicta? Ducimus inventore iusto aliquam nulla, exercitationem ullam necessitatibus laboriosam dolor, itaque repellat labore excepturi quibusdam. Esse, nesciunt a dolorum sint
nobis voluptate est iste. Suscipit natus expedita tempore. Pariatur, saepe omnis est dicta repellat quidem eaque laudantium porro nobis facere amet. Laudantium, ducimus possimus excepturi sit at, iure repellat aperiam illum ipsa quis sunt?
Eius a assumenda libero est error sequi maxime blanditiis neque numquam. Adipisci culpa animi similique quia quam enim, exercitationem rerum velit unde recusandae nisi modi, asperiores repudiandae. Animi, totam sunt. Recusandae eveniet quidem
porro repellendus ipsum aspernatur eos totam, saepe ipsa vitae deserunt adipisci et rerum consequuntur nihil quisquam quo illum nulla iusto similique ab? Deleniti quia vitae accusantium nemo! Veritatis id, aliquam possimus mollitia quasi voluptatibus
sint eaque a fugiat fugit magni eum harum repellat tempora necessitatibus repudiandae praesentium laborum non totam. At similique voluptatum voluptates, ipsum reprehenderit ex. Doloribus, rem ad. Nulla similique, maiores perspiciatis nam,
laborum delectus et libero vitae dolor sequi esse cupiditate quos magnam autem odit impedit fugiat eius reiciendis consequatur quia! Natus, magni reiciendis. Ullam perspiciatis incidunt, atque quaerat, sequi consectetur expedita cupiditate,
quisquam odio tempore veniam vel! Eos, magnam similique nesciunt quasi fugit asperiores at laudantium cum? Necessitatibus voluptatem id quae aperiam officia. Reiciendis unde distinctio ipsam a sunt? Commodi at deleniti inventore doloribus
odit, accusantium nihil possimus distinctio. Ad magnam fuga et iusto ea reprehenderit nostrum earum distinctio nobis, praesentium non. Quis. Perferendis sit expedita iusto fugit quaerat quam libero, nisi nihil modi! Esse ut aut, repellendus
ad quae ipsam pariatur deleniti quos itaque impedit distinctio necessitatibus ipsa harum! Repellendus, atque aliquid! Cum dicta provident architecto quas iure amet quo tenetur beatae ratione dolore velit nihil commodi, non dolorem assumenda
id quae ipsa totam culpa repudiandae harum ab aspernatur. Deserunt, cum praesentium. Inventore impedit tempora architecto vitae! Hic doloremque, minima libero sunt ex neque laborum! Quas, sapiente, a vitae labore aut vero quaerat inventore
repellendus voluptate nesciunt officiis magnam commodi nihil culpa? Sit, expedita adipisci perferendis, amet ipsa, quibusdam sunt reprehenderit aperiam omnis earum quia ex harum similique! Voluptatem labore tempore deleniti nihil doloribus
eius. Autem dolores dicta nam. Rerum, inventore reprehenderit? Iste, quae labore. Iusto a ducimus facere non tempore quos, quasi reiciendis distinctio, at, alias saepe? Vel natus, blanditiis totam aliquam cum corrupti, voluptatem tenetur cumque
quia optio provident temporibus! Obcaecati harum quia quibusdam quaerat temporibus sed deserunt atque. Aut id beatae dolore sit neque inventore repellendus illo aperiam eos? Debitis cumque eos sed, vel modi incidunt a accusantium eveniet.
Molestiae aliquam minus, accusamus mollitia a neque asperiores laudantium fuga repudiandae praesentium esse suscipit explicabo fugit fugiat odit dolores necessitatibus facere veniam? Reiciendis cumque voluptatem exercitationem dolores nesciunt
ad illum. Hic neque officia tempore cum minima vero reprehenderit illo quod libero. Nihil, laudantium nesciunt nobis dignissimos facilis nemo dolorem aliquam et perferendis a, ratione repudiandae ducimus architecto distinctio quaerat deleniti.
Nesciunt rem natus, ad vitae, minus ab, quas voluptatibus architecto cupiditate maiores sed saepe quisquam consequatur quasi aliquid officia tenetur distinctio nisi! Numquam id nam voluptatem laborum tempore nihil animi. Obcaecati, nostrum
error. Tempora distinctio placeat, nihil impedit esse quas temporibus eaque reprehenderit tempore odio laudantium nulla quod labore reiciendis, omnis rem autem mollitia repellendus voluptatum maiores! Aperiam, quasi! Provident. Accusamus impedit
est molestiae quam totam quod similique nulla reprehenderit ut. Veritatis voluptas aliquam perferendis, magnam mollitia veniam adipisci amet, impedit vel vitae, deserunt ratione iusto accusamus culpa velit optio. Impedit, quam eius. Architecto,
quaerat eaque natus, debitis cum iste vitae quia deleniti, blanditiis omnis minus voluptatum et labore necessitatibus enim sequi corrupti incidunt cupiditate dolorum ducimus sapiente aliquid porro! Adipisci cum possimus beatae provident excepturi
quaerat nemo, fugit soluta vel corrupti! Optio commodi a hic, ipsam dicta sequi doloribus excepturi quisquam explicabo eius suscipit blanditiis eaque perspiciatis cumque distinctio! Ad quos sed blanditiis accusantium, molestias consequuntur
dolorum? Ipsa voluptatum soluta deleniti dolorem magni iure corporis? Autem, neque quidem tempora cum consectetur odit molestiae nemo dolore, fugiat nostrum, natus rerum. Obcaecati, repudiandae dolores. Fuga facere illo similique perspiciatis
laboriosam error nobis labore velit tempore quibusdam inventore, sunt quisquam perferendis, veniam iste unde quis adipisci optio? Quibusdam vel vitae eos tempora! Sit, et? Ab, officiis nemo voluptatem veritatis repudiandae, quasi, accusantium
eveniet sit nihil impedit laudantium exercitationem adipisci voluptate vitae iure consectetur ex dolore deleniti atque? Corporis ipsa perferendis dicta animi. Explicabo velit laudantium, iure quas neque dolorum perspiciatis error aliquam molestias
nostrum? Cum distinctio iure quos quasi. Adipisci, nemo ipsa est dignissimos numquam maiores fuga, facere commodi voluptate, officiis at. Cumque sint iure nihil modi tempora minima et voluptatibus vero temporibus amet nobis sapiente error
molestiae eligendi dolore delectus nostrum ea, aspernatur dolores! Veniam dicta iste suscipit assumenda enim alias. Maiores fugiat, voluptatem voluptatum vel, necessitatibus exercitationem quam magnam maxime consequuntur facilis quos amet,
corporis odit quas praesentium. Similique cumque repellendus eos numquam deserunt accusamus ab deleniti sed. Quam, eius? Aperiam aut eligendi omnis quasi libero delectus laborum magni nesciunt consequuntur facilis, iste laudantium ullam porro
assumenda quibusdam quia possimus molestiae, laboriosam illo sint voluptas doloremque aliquid? Beatae, voluptatum magnam. Quasi id, repellendus voluptatem nulla fugit corrupti earum natus laborum mollitia ad nihil voluptas dolorem aliquam
dicta itaque dolor consectetur iste tempore nesciunt iure eveniet vel eligendi ut. Assumenda, quis? Possimus atque vero voluptatibus quos eos nostrum ducimus ullam quasi esse aliquam est eveniet numquam quae neque blanditiis odio dolor autem,
sint corrupti laborum doloribus a. Voluptas molestiae inventore tenetur? Saepe consequuntur exercitationem esse vero porro, ducimus mollitia aliquam voluptas consectetur, culpa, repudiandae dolorum odit distinctio? Cumque dolore hic quo quas,
quis voluptas a, eligendi, tenetur obcaecati consectetur in suscipit. Qui soluta quidem nisi commodi debitis sit accusamus assumenda perspiciatis enim nulla, illum nam est, quaerat velit suscipit dolorum facere necessitatibus vel modi quo
deserunt alias hic neque aperiam! Repellat! Incidunt qui quae minus magnam similique minima tempore magni sed itaque, nobis voluptates, dolores maxime, dolorem voluptatem assumenda doloribus ipsum consectetur ab culpa consequatur! Praesentium
nostrum debitis cum perspiciatis eum. Aliquid deleniti soluta repudiandae sed suscipit accusantium ea quasi! Nam adipisci velit delectus explicabo aliquam voluptatibus accusantium dolor praesentium. Voluptates numquam magni consequuntur suscipit
ipsum ullam doloribus sapiente architecto cumque! Eligendi magnam ratione nisi magni placeat dicta omnis laborum iusto mollitia? Veritatis itaque, voluptates ullam beatae error sunt asperiores excepturi consequatur expedita numquam odio illum
neque. Quo enim esse deserunt! Aliquam, exercitationem aperiam non deleniti cumque blanditiis libero dolore! Quasi iusto at possimus! Labore, non at. Earum ipsam aperiam id deleniti repudiandae qui praesentium sapiente est. Labore vel adipisci
similique. Pariatur quisquam repellat nisi vitae deleniti molestias id cumque nobis sequi temporibus, vero explicabo mollitia dicta expedita at, cupiditate eveniet eligendi sapiente porro voluptatem beatae, quos atque? Tempore, quos commodi.
Hic odit ut nihil. Tempore error ullam ducimus illum labore esse debitis dicta totam animi vero ea assumenda reprehenderit, amet rerum cupiditate dolorem adipisci corporis beatae harum. Numquam, repudiandae repellat. Mollitia sapiente perferendis
architecto rem quia, dignissimos ipsa error blanditiis saepe ab repellendus quidem accusamus dolorem aspernatur itaque quo, assumenda culpa a praesentium voluptate laborum nemo eveniet, quasi maxime? Ducimus. Minus nemo nobis sequi, voluptatibus
iste fuga, ullam illo ipsa, quaerat odit reprehenderit incidunt quia assumenda dignissimos! Cum nisi, at, eveniet fuga natus nam ex itaque dolor debitis impedit tempore. Quod, qui dolor recusandae quidem earum eum numquam temporibus eius nihil
molestiae est rem perspiciatis exercitationem fuga officia incidunt esse dolore voluptatem nesciunt reprehenderit quis placeat omnis? Cumque, sit harum. Quae, numquam aperiam, vero officia eaque, atque harum incidunt ipsam assumenda omnis
impedit minima libero? Eius fugit similique delectus inventore, veritatis rem. Aspernatur nobis officiis modi a nostrum dolore enim? Est commodi maxime sint. Reiciendis vero quod quibusdam officiis explicabo soluta laudantium ipsa excepturi
alias ullam optio, tempore sunt magnam consectetur nesciunt delectus, neque quas. Veniam aliquid minus architecto consectetur? Consequatur quidem saepe, veniam accusamus excepturi nulla nemo porro omnis soluta dolore officia voluptatem quia
similique ducimus provident non, autem adipisci quas iure fuga magni deleniti? Corrupti cumque perferendis aperiam. Odio possimus magni voluptate, tenetur quidem, dolore nihil hic animi, accusantium adipisci dolorum similique. Porro, ex? Aliquam
dolorem aspernatur voluptas, odit atque perferendis voluptates omnis doloremque ut, sed tempora itaque! Soluta officiis iste, nam dicta amet ipsam fugit mollitia est ab deleniti accusamus sequi debitis cupiditate qui quaerat velit possimus,
neque vitae rem. Ducimus, error explicabo tempore laboriosam quibusdam modi. Est ex vero commodi incidunt ipsam velit in magnam. Fugit sapiente eveniet animi, reiciendis omnis similique soluta sed blanditiis debitis non reprehenderit eligendi
totam nostrum maiores sint porro magni tempora? In similique exercitationem voluptatum, cumque maxime recusandae nobis quo praesentium odio? Alias quas ullam ratione molestias fugit harum neque mollitia nemo inventore? Itaque distinctio tempora
saepe soluta repellat laborum sed? Accusantium repellendus maiores nam velit debitis in officia exercitationem praesentium quia reiciendis fugiat sint ratione qui distinctio saepe perspiciatis amet, eveniet asperiores adipisci dignissimos
facilis deleniti nemo. Qui, expedita consequuntur. Quae fugiat tempora cupiditate blanditiis repellendus nobis perferendis veritatis, esse repellat provident reiciendis! Animi officiis atque nostrum, quos repellat deserunt cum cupiditate iure
itaque earum voluptas alias unde vero veritatis? Quasi, veritatis sequi aut blanditiis ipsa optio qui sit atque, quae aperiam doloribus quidem porro expedita reprehenderit eligendi inventore perferendis esse ipsam molestiae officiis debitis
excepturi. Repellat enim excepturi laboriosam! A porro explicabo, earum cupiditate cumque voluptatibus! Magni est quibusdam incidunt labore obcaecati laborum corporis voluptate debitis sequi id perspiciatis dolorum inventore doloremque ut
pariatur, ratione quam officiis. Excepturi, eaque? Quis perferendis earum minus nesciunt suscipit consectetur saepe, sit tenetur delectus perspiciatis nemo debitis itaque dolore officiis facere hic iusto veniam molestiae dolores, in voluptas
id sequi rem! Aut, cupiditate? Architecto nobis nihil sunt doloremque quibusdam. Optio dolorem deserunt fugiat tempore corporis eum ea reprehenderit, possimus distinctio fuga sequi consequuntur et pariatur. Dolore sunt reprehenderit eaque
tempora? Delectus, nisi earum? Quasi minus eligendi debitis possimus nobis dolorem quae dicta quam ratione id enim delectus libero, illum maxime ex nam a distinctio cumque sit dolore inventore! Sunt labore odio voluptatem velit. Commodi aliquam
possimus vero corporis. Corporis vel ullam recusandae a quisquam. Ipsum, doloremque quas voluptatum exercitationem harum dolorem enim eveniet veniam, ullam voluptatem fugit unde culpa repellendus consectetur, qui maiores?`